# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/karl/dev/ph5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/karl/dev/ph5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/karl/dev/ph5/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karl/dev/ph5/CMakeFiles /home/karl/dev/ph5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karl/dev/ph5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _ph5

# Build rule for target.
_ph5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _ph5
.PHONY : _ph5

# fast build rule for target.
_ph5/fast:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/build
.PHONY : _ph5/fast

#=============================================================================
# Target rules for targets named ph5

# Build rule for target.
ph5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ph5
.PHONY : ph5

# fast build rule for target.
ph5/fast:
	$(MAKE) -f CMakeFiles/ph5.dir/build.make CMakeFiles/ph5.dir/build
.PHONY : ph5/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

Complex.o: Complex.cpp.o
.PHONY : Complex.o

# target to build an object file
Complex.cpp.o:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/Complex.cpp.o
.PHONY : Complex.cpp.o

Complex.i: Complex.cpp.i
.PHONY : Complex.i

# target to preprocess a source file
Complex.cpp.i:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/Complex.cpp.i
.PHONY : Complex.cpp.i

Complex.s: Complex.cpp.s
.PHONY : Complex.s

# target to generate assembly for a file
Complex.cpp.s:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/Complex.cpp.s
.PHONY : Complex.cpp.s

FireLog.o: FireLog.cpp.o
.PHONY : FireLog.o

# target to build an object file
FireLog.cpp.o:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/FireLog.cpp.o
.PHONY : FireLog.cpp.o

FireLog.i: FireLog.cpp.i
.PHONY : FireLog.i

# target to preprocess a source file
FireLog.cpp.i:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/FireLog.cpp.i
.PHONY : FireLog.cpp.i

FireLog.s: FireLog.cpp.s
.PHONY : FireLog.s

# target to generate assembly for a file
FireLog.cpp.s:
	$(MAKE) -f CMakeFiles/_ph5.dir/build.make CMakeFiles/_ph5.dir/FireLog.cpp.s
.PHONY : FireLog.cpp.s

ph5.o: ph5.cpp.o
.PHONY : ph5.o

# target to build an object file
ph5.cpp.o:
	$(MAKE) -f CMakeFiles/ph5.dir/build.make CMakeFiles/ph5.dir/ph5.cpp.o
.PHONY : ph5.cpp.o

ph5.i: ph5.cpp.i
.PHONY : ph5.i

# target to preprocess a source file
ph5.cpp.i:
	$(MAKE) -f CMakeFiles/ph5.dir/build.make CMakeFiles/ph5.dir/ph5.cpp.i
.PHONY : ph5.cpp.i

ph5.s: ph5.cpp.s
.PHONY : ph5.s

# target to generate assembly for a file
ph5.cpp.s:
	$(MAKE) -f CMakeFiles/ph5.dir/build.make CMakeFiles/ph5.dir/ph5.cpp.s
.PHONY : ph5.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... _ph5"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... ph5"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Complex.o"
	@echo "... Complex.i"
	@echo "... Complex.s"
	@echo "... FireLog.o"
	@echo "... FireLog.i"
	@echo "... FireLog.s"
	@echo "... ph5.o"
	@echo "... ph5.i"
	@echo "... ph5.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

