#! /bin/bash

echo "SCRIPT	: buildzip"
echo "HELP	: build zip file for Arduino installation"

TAG=`git log --pretty=format:'%H' -n 1`
OUTPUT="ph5-$TAG.zip"
echo "STATUS	: creating $OUTPUT"

rm -f $OUTPUT

cd ..

zip -r $OUTPUT \
	ph5/CHANGELOG.md \
	ph5/LICENSE.md \
	ph5/README.md \
	ph5/*.cpp \
	ph5/*.h \
	ph5/*.hpp \
	-x \
	ph5/ph5.cpp 
